singleuser:
  image:
    # name: jupyter/all-spark-notebook
    # tag: spark-3.1.1
    name: jupyter/pyspark-notebook
    tag: latest
  extraEnv:
    EDITOR: "vim"
    SPARK_MASTER_IP: "k8s://https://172.20.0.2:6443"
    SPARK_SUBMIT_DEPLOY_MODE: "client"
  cmd: null
  serviceAccountName: jupyter-notebook-sa
