---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-notebook-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyter-notebook-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyter-notebook-binding
subjects:
  - kind: ServiceAccount
    name: jupyter-notebook-sa
roleRef:
  kind: Role
  name: jupyter-notebook-role
  apiGroup: rbac.authorization.k8s.io
